name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx-hello:latest .

    - name: Push Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/nginx-hello:latest

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl apply -f k8s/ingress.yaml
        kubectl apply -f k8s/hpa.yaml

    - name: Wait for deployment
      run: |
        kubectl rollout restart deployment/nginx-deployment
        kubectl rollout status deployment/nginx-deployment

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2
      with:
        projectBaseDir: .
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
